name: Deploy Node.js API to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a stable version for backend

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Upload backend files to EC2
        run: |
         scp -o StrictHostKeyChecking=no -r api ubuntu@13.51.171.2:/home/ubuntu/tmp-api/

      - name: Replace backend and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.171.2 << 'EOF'
            sudo rm -rf /home/ubuntu/onstep/api/*
            sudo mv /home/ubuntu/tmp-api/* /home/ubuntu/onstep/api/
            cd /home/ubuntu/onstep/api
            npm install
            pm2 restart app.js || pm2 start app.js --name api
          EOF
